"use strict";
/* ─────────────────────────────────────────────
   DEFAULT TRACKS — generated by Web Audio API
   These 5 tracks are real synthesized audio
   that plays immediately with zero loading
───────────────────────────────────────────── */
const EMOJIS = ["🌌","🎹","🌊","🌅","🌿"];
const COLORS = {
  bg:  ["#1a1025","#0d1a25","#001520","#1f1800","#0a1a0a"],
  bar: ["#7c4dcc","#00b4d8","#0077b6","#e8c97a","#2d6a4f"],
};
/* ─────────────────────────────────────────────
   STATE
───────────────────────────────────────────── */
let tracks      = [];   // { name, artist, src (blob url or null), emoji, bg, bar, dur }
let curIdx      = 0;
let isPlaying   = false;
let shuffleOn   = false;
let repeatOn    = false;
let liked       = new Set();
let rafId       = null;
let waveSnap    = [];   // static waveform snapshot per track
let audioCtx    = null;
let analyser    = null;
let sourceNode  = null;
/* ─────────────────────────────────────────────
   HTML5 AUDIO — the actual engine
───────────────────────────────────────────── */
const audio       = new Audio();
audio.preload     = "auto";
audio.volume      = 0.8;
/* ─────────────────────────────────────────────
   WEB AUDIO API — for real-time visualiser
───────────────────────────────────────────── */
function initAudioContext() {
  if (audioCtx) return;
  audioCtx  = new (window.AudioContext || window.webkitAudioContext)();
  analyser  = audioCtx.createAnalyser();
  analyser.fftSize = 128;
  const src = audioCtx.createMediaElementSource(audio);
  src.connect(analyser);
  analyser.connect(audioCtx.destination);
}
/* ─────────────────────────────────────────────
   SYNTHESISE DEFAULT TRACKS using Web Audio API
   Each track is a short loopable melody rendered
   to an AudioBuffer then converted to a Blob URL
───────────────────────────────────────────── */
function synthTrack(index) {
  return new Promise(resolve => {
    const SR      = 22050;
    const DUR     = 30;          // 30 seconds each
    const FRAMES  = SR * DUR;
    const ctx     = new OfflineAudioContext(2, FRAMES, SR);
    const CONFIGS = [
      // 0 — Chill Lo-fi
      { base: 220, chords: [1, 1.25, 1.5, 2], bpm: 72,  type: "sine",   reverb: 0.4, pad: true  },
      // 1 — Dreamy Piano
      { base: 261, chords: [1, 1.19, 1.5, 1.78], bpm: 80, type: "triangle", reverb: 0.5, pad: false },
      // 2 — Deep Ocean Ambient
      { base: 110, chords: [1, 1.33, 1.5, 2], bpm: 60, type: "sine", reverb: 0.7, pad: true },
      // 3 — Sunny Ukulele
      { base: 330, chords: [1, 1.25, 1.5, 2], bpm: 100, type: "sawtooth", reverb: 0.2, pad: false },
      // 4 — Forest Calm
      { base: 174, chords: [1, 1.19, 1.41, 1.78], bpm: 65, type: "sine", reverb: 0.6, pad: true },
    ];
    const C   = CONFIGS[index];
    const BPL = 60 / C.bpm;      // beats per second → seconds per beat
    // Master gain
    const master = ctx.createGain();
    master.gain.value = 0.55;
    master.connect(ctx.destination);
    // Simple reverb (convolver with impulse)
    const conv  = ctx.createConvolver();
    const iLen  = Math.floor(SR * 1.5);
    const iBuf  = ctx.createBuffer(2, iLen, SR);
    for (let ch = 0; ch < 2; ch++) {
      const d = iBuf.getChannelData(ch);
      for (let i = 0; i < iLen; i++) d[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / iLen, 3);
    }
    conv.buffer = iBuf;
    conv.connect(master);
    const dryGain = ctx.createGain(); dryGain.gain.value = 1 - C.reverb; dryGain.connect(master);
    const wetGain = ctx.createGain(); wetGain.gain.value = C.reverb;     wetGain.connect(conv);
    // Note scheduler
    const notes = [];
    const pattern = C.chords;
    let t = 0.05;
    while (t < DUR - 2) {
      pattern.forEach((ratio, i) => {
        notes.push({ freq: C.base * ratio, start: t + i * BPL * 0.5, dur: BPL * 1.8 });
      });
      t += BPL * pattern.length * 0.5;
    }
    notes.forEach(n => {
      if (n.start >= DUR) return;
      const osc  = ctx.createOscillator();
      const env  = ctx.createGain();
      osc.type   = C.type;
      osc.frequency.value = n.freq;
      // Slight detune for warmth
      osc.detune.value = (Math.random() - 0.5) * 8;
      env.gain.setValueAtTime(0, n.start);
      env.gain.linearRampToValueAtTime(0.18, n.start + 0.04);
      env.gain.setValueAtTime(0.18, n.start + n.dur - 0.15);
      env.gain.linearRampToValueAtTime(0, n.start + n.dur);
      osc.connect(env);
      env.connect(dryGain);
      env.connect(wetGain);
      osc.start(n.start);
      osc.stop(n.start + n.dur + 0.01);
    });
    // Low sub pad
    if (C.pad) {
      const pad  = ctx.createOscillator();
      const penv = ctx.createGain();
      pad.type   = "sine";
      pad.frequency.value = C.base * 0.5;
      penv.gain.value = 0.12;
      pad.connect(penv);
      penv.connect(dryGain);
      pad.start(0); pad.stop(DUR);
    }
    ctx.startRendering().then(buf => {
      // Convert AudioBuffer → WAV Blob → Object URL
      const wav = audioBufferToWav(buf);
      const url = URL.createObjectURL(new Blob([wav], { type: "audio/wav" }));
      resolve(url);
    }).catch(() => resolve(null));
  });
}
/* ─────────────────────────────────────────────
   AudioBuffer → WAV ArrayBuffer helper
───────────────────────────────────────────── */
function audioBufferToWav(buf) {
  const numCh  = buf.numberOfChannels;
  const len    = buf.length;
  const SR     = buf.sampleRate;
  const bpe    = 2;                    // bytes per sample (16-bit)
  const total  = 44 + len * numCh * bpe;
  const ab     = new ArrayBuffer(total);
  const view   = new DataView(ab);
  function str(offset, s) { for (let i = 0; i < s.length; i++) view.setUint8(offset + i, s.charCodeAt(i)); }
  function u16(o, v) { view.setUint16(o, v, true); }
  function u32(o, v) { view.setUint32(o, v, true); }
  str(0,  "RIFF"); u32(4,  total - 8); str(8, "WAVE");
  str(12, "fmt "); u32(16, 16);        u16(20, 1);
  u16(22, numCh); u32(24, SR);         u32(28, SR * numCh * bpe);
  u16(32, numCh * bpe); u16(34, 16);
  str(36, "data"); u32(40, len * numCh * bpe);
  let offset = 44;
  for (let i = 0; i < len; i++) {
    for (let ch = 0; ch < numCh; ch++) {
      const s = Math.max(-1, Math.min(1, buf.getChannelData(ch)[i]));
      view.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7FFF, true);
      offset += 2;
    }
  }
  return ab;
}
/* ─────────────────────────────────────────────
   TRACK METADATA
───────────────────────────────────────────── */
const TRACK_NAMES = [
  { name: "Midnight Pulse",   artist: "Lumina Synth"  },
  { name: "Dream Keys",       artist: "Ivory Echo"    },
  { name: "Ocean Depth",      artist: "Ambient Works" },
  { name: "Morning Light",    artist: "Lo-Fi Lab"     },
  { name: "Forest Silence",   artist: "Nature Tones"  },
];
/* ─────────────────────────────────────────────
   WAVEFORM SNAPSHOT (static, per track)
───────────────────────────────────────────── */
function genWaveSnap(seed) {
  const N = 60; let v = 0.5; const d = [];
  for (let i = 0; i < N; i++) {
    v = Math.max(0.08, Math.min(1, v + Math.sin(seed * i + i * .4) * .18 + (Math.random() - .5) * .22));
    d.push(v);
  }
  return d;
}
/* ─────────────────────────────────────────────
   CANVAS DRAW — two modes:
   1. Static waveform (when paused / no audio ctx)
   2. Live frequency visualiser (when playing)
───────────────────────────────────────────── */
const canvas = document.getElementById("vis-canvas");
const ctx2d  = canvas.getContext("2d");
function drawCanvas() {
  const W = canvas.parentElement.clientWidth || 400;
  const H = 40;
  canvas.width  = W * 2; canvas.height = H * 2;
  canvas.style.width = W + "px"; canvas.style.height = H + "px";
  ctx2d.scale(2, 2);
  ctx2d.clearRect(0, 0, W, H);
  const color = tracks[curIdx] ? tracks[curIdx].bar : "#e8c97a";
  let bars;
  if (analyser && isPlaying) {
    // LIVE visualiser
    const freqData = new Uint8Array(analyser.frequencyBinCount);
    analyser.getByteFrequencyData(freqData);
    bars = Array.from(freqData).slice(0, 60).map(v => v / 255);
  } else {
    // Static waveform snapshot
    bars = waveSnap;
    if (!bars || !bars.length) bars = genWaveSnap(curIdx * 7 + 13);
  }
  const played  = audio.duration ? audio.currentTime / audio.duration : 0;
  const bw      = (W - bars.length) / bars.length;
  bars.forEach((v, i) => {
    const barH = Math.max(2, v * H * 0.82);
    const x    = i * (bw + 1);
    const y    = (H - barH) / 2;
    const done = i / bars.length < played;
    ctx2d.fillStyle = done ? color : "rgba(255,255,255,0.08)";
    ctx2d.beginPath();
    if (ctx2d.roundRect) ctx2d.roundRect(x, y, Math.max(bw, 1), barH, 2);
    else ctx2d.rect(x, y, Math.max(bw, 1), barH);
    ctx2d.fill();
  });
}
function startVisLoop() {
  cancelAnimationFrame(rafId);
  function loop() { drawCanvas(); rafId = requestAnimationFrame(loop); }
  loop();
}
function stopVisLoop() {
  cancelAnimationFrame(rafId);
  drawCanvas();
}
/* ─────────────────────────────────────────────
   DOM REFS
───────────────────────────────────────────── */
const $ = id => document.getElementById(id);
const disc      = $("disc");
const discEmoji = $("disc-emoji");
const dispName  = $("disp-name");
const dispArt   = $("disp-artist");
const progBar   = $("prog-bar");
const progFill  = $("prog-fill");
const tCur      = $("t-cur");
const tDur      = $("t-dur");
const btnPlay   = $("btn-play");
const btnPrev   = $("btn-prev");
const btnNext   = $("btn-next");
const btnBack   = $("btn-back");
const btnFwd    = $("btn-fwd");
const btnShuffle= $("btn-shuffle");
const btnRepeat = $("btn-repeat");
const btnLike   = $("btn-like");
const volSl     = $("vol-sl");
const volIc     = $("vol-ic");
const volVal    = $("vol-val");
const liveDot   = $("live-dot");
const fileInput = $("file-input");
const statusBadge=$("status-badge");
/* ─────────────────────────────────────────────
   UTILITIES
───────────────────────────────────────────── */
function fmt(s) {
  if (!isFinite(s) || s < 0) return "0:00";
  return Math.floor(s/60) + ":" + String(Math.floor(s%60)).padStart(2,"0");
}
/* ─────────────────────────────────────────────
   BUILD PLAYLIST UI
───────────────────────────────────────────── */
function buildList() {
  const list = $("track-list");
  list.innerHTML = "";
  $("track-count").textContent = tracks.length + " track" + (tracks.length !== 1 ? "s" : "");
  tracks.forEach((t, i) => {
    const row = document.createElement("div");
    row.className = "track-item" + (i === curIdx ? " active" : "");
    row.innerHTML = `
      <span class="track-index">${String(i+1).padStart(2,"0")}</span>
      <div class="track-thumb" style="background:${t.bg}">${t.emoji}</div>
      <div class="track-info">
        <div class="track-name">${t.name}</div>
        <div class="track-artist">${t.artist}</div>
      </div>
      <span class="track-dur">${t.dur ? fmt(t.dur) : "--:--"}</span>`;
    row.onclick = () => { loadTrack(i); startPlay(); };
    list.appendChild(row);
  });
}
/* ─────────────────────────────────────────────
   LOAD TRACK
───────────────────────────────────────────── */
function loadTrack(i) {
  curIdx = i;
  const t = tracks[i];
  dispName.textContent = t.name;
  dispArt.textContent  = t.artist.toUpperCase();
  disc.style.background = t.bg;
  discEmoji.textContent = t.emoji;
  tCur.textContent = "0:00";
  tDur.textContent = t.dur ? fmt(t.dur) : "--:--";
  progFill.style.width = "0%";
  waveSnap = t.snap || genWaveSnap(i * 7 + 13);
  syncLike();
  buildList();
  if (t.src) {
    audio.src = t.src;
    audio.load();
  }
  drawCanvas();
}
/* ─────────────────────────────────────────────
   PLAY / PAUSE
───────────────────────────────────────────── */
function startPlay() {
  if (!tracks.length) return;
  initAudioContext();
  if (audioCtx.state === "suspended") audioCtx.resume();
  audio.play().then(() => {
    isPlaying = true;
    disc.classList.add("spinning");
    disc.classList.remove("paused-spin");
    btnPlay.textContent = "⏸";
    liveDot.classList.add("on");
    startVisLoop();
  }).catch(e => {
    console.warn("Playback error:", e);
  });
}
function pausePlay() {
  audio.pause();
  isPlaying = false;
  disc.classList.remove("spinning");
  disc.classList.add("paused-spin");
  btnPlay.textContent = "▶";
  liveDot.classList.remove("on");
  stopVisLoop();
}
function togglePlay() {
  if (!tracks.length) return;
  isPlaying ? pausePlay() : startPlay();
}
/* ─────────────────────────────────────────────
   AUDIO EVENTS
───────────────────────────────────────────── */
audio.addEventListener("loadedmetadata", () => {
  tDur.textContent = fmt(audio.duration);
  if (tracks[curIdx]) {
    tracks[curIdx].dur = audio.duration;
    buildList();
  }
});
audio.addEventListener("timeupdate", () => {
  if (!audio.duration) return;
  const p = audio.currentTime / audio.duration;
  progFill.style.width = (p * 100) + "%";
  tCur.textContent = fmt(audio.currentTime);
  if (!isPlaying) drawCanvas(); // update waveform fill while seeking
});
audio.addEventListener("ended", () => {
  if (repeatOn) { audio.currentTime = 0; startPlay(); return; }
  const next = shuffleOn
    ? Math.floor(Math.random() * tracks.length)
    : (curIdx + 1) % tracks.length;
  if (!shuffleOn && curIdx === tracks.length - 1) { pausePlay(); return; }
  loadTrack(next); startPlay();
});
/* ─────────────────────────────────────────────
   SEEK
───────────────────────────────────────────── */
function seek(e, el) {
  if (!audio.duration) return;
  const r = el.getBoundingClientRect();
  audio.currentTime = Math.max(0, Math.min(1, (e.clientX - r.left) / r.width)) * audio.duration;
}
progBar.addEventListener("click", e => seek(e, progBar));
$("vis-zone").addEventListener("click", e => seek(e, $("vis-zone")));
/* ─────────────────────────────────────────────
   LIKE
───────────────────────────────────────────── */
function syncLike() {
  const on = liked.has(curIdx);
  btnLike.textContent = on ? "♥" : "♡";
  btnLike.className   = "sact" + (on ? " liked" : "");
}
btnLike.onclick = () => {
  liked.has(curIdx) ? liked.delete(curIdx) : liked.add(curIdx);
  syncLike();
};
/* ─────────────────────────────────────────────
   CONTROLS
───────────────────────────────────────────── */
btnPlay.onclick = togglePlay;
btnPrev.onclick = () => {
  if (audio.currentTime > 3) { audio.currentTime = 0; return; }
  const p = shuffleOn ? Math.floor(Math.random()*tracks.length) : (curIdx - 1 + tracks.length) % tracks.length;
  loadTrack(p); if (isPlaying) startPlay();
};
btnNext.onclick = () => {
  const n = shuffleOn ? Math.floor(Math.random()*tracks.length) : (curIdx + 1) % tracks.length;
  loadTrack(n); if (isPlaying) startPlay();
};
btnBack.onclick = () => { audio.currentTime = Math.max(0, audio.currentTime - 10); };
btnFwd.onclick  = () => { audio.currentTime = Math.min(audio.duration||0, audio.currentTime + 10); };
btnShuffle.onclick = function() { shuffleOn = !shuffleOn; this.classList.toggle("on", shuffleOn); this.setAttribute("aria-pressed", shuffleOn); };
btnRepeat.onclick  = function() { repeatOn  = !repeatOn;  this.classList.toggle("on", repeatOn);  this.setAttribute("aria-pressed", repeatOn); };
/* ─────────────────────────────────────────────
   VOLUME
───────────────────────────────────────────── */
function updateVol() {
  const v = parseInt(volSl.value);
  audio.volume = v / 100;
  volVal.textContent = v;
  volIc.textContent  = v === 0 ? "🔇" : v < 40 ? "🔉" : "🔊";
  volSl.style.background = `linear-gradient(90deg,rgba(255,255,255,.4) ${v}%,rgba(255,255,255,.08) ${v}%)`;
}
volSl.addEventListener("input", updateVol);
/* ─────────────────────────────────────────────
   FILE UPLOAD — play local mp3/wav/ogg files
───────────────────────────────────────────── */
fileInput.addEventListener("change", e => {
  const files = Array.from(e.target.files);
  if (!files.length) return;
  const newTracks = files.map((f, i) => {
    const url  = URL.createObjectURL(f);
    const name = f.name.replace(/\.[^.]+$/, "").replace(/[-_]+/g, " ");
    const idx  = (tracks.length + i) % 5;
    return {
      name,
      artist: "Your Music",
      src:    url,
      emoji:  EMOJIS[idx],
      bg:     COLORS.bg[idx],
      bar:    COLORS.bar[idx],
      snap:   genWaveSnap((tracks.length + i) * 7 + 99),
      dur:    null,
    };
  });
  const startAt = tracks.length;
  tracks.push(...newTracks);
  buildList();
  statusBadge.style.display = "inline";
  statusBadge.textContent   = files.length + " file" + (files.length > 1 ? "s" : "") + " added";
  setTimeout(() => statusBadge.style.display = "none", 3000);
  // Auto-play first uploaded track
  loadTrack(startAt);
  startPlay();
});
/* ─────────────────────────────────────────────
   KEYBOARD SHORTCUTS
───────────────────────────────────────────── */
document.addEventListener("keydown", e => {
  if (e.target.tagName === "INPUT") return;
  if (e.code === "Space")      { e.preventDefault(); togglePlay(); }
  if (e.code === "ArrowRight") btnFwd.click();
  if (e.code === "ArrowLeft")  btnBack.click();
  if (e.code === "ArrowUp")    { e.preventDefault(); volSl.value = Math.min(100, +volSl.value + 5); updateVol(); }
  if (e.code === "ArrowDown")  { e.preventDefault(); volSl.value = Math.max(0,   +volSl.value - 5); updateVol(); }
  if (e.code === "KeyN") btnNext.click();
  if (e.code === "KeyP") btnPrev.click();
  if (e.code === "KeyL") btnLike.click();
});
window.addEventListener("resize", drawCanvas);
/* ─────────────────────────────────────────────
   INIT — synthesise 5 default tracks
───────────────────────────────────────────── */
(async function init() {
  updateVol();
  dispName.textContent = "Generating audio...";
  dispArt.textContent  = "Please wait a moment";
  // Build track stubs first so UI shows
  for (let i = 0; i < 5; i++) {
    tracks.push({
      name:   TRACK_NAMES[i].name,
      artist: TRACK_NAMES[i].artist,
      src:    null,
      emoji:  EMOJIS[i],
      bg:     COLORS.bg[i],
      bar:    COLORS.bar[i],
      snap:   genWaveSnap(i * 7 + 13),
      dur:    30,
    });
  }
  buildList();
  drawCanvas();
  // Synthesise audio in background — parallel
  const urls = await Promise.all([0,1,2,3,4].map(i => synthTrack(i)));
  urls.forEach((url, i) => { if (url) tracks[i].src = url; });
  // Load first track
  loadTrack(0);
  dispName.textContent = TRACK_NAMES[0].name;
  dispArt.textContent  = TRACK_NAMES[0].artist.toUpperCase();
  buildList();
  drawCanvas();
})();